### ISSUE TITLE
This tool is great 🙏

### ISSUE THREAD

**Issue by kimmobrunfeldt** [daxelrod/jowl#4]
Not an issue, just wanted to say this tool is **exactly** I was looking for.

**Comment by daxelrod** [comment]
This issue made my day. It's great to know that I'm not the only one with this particular itch.

I want to assure you that jowl isn't abandoned, I've just had way less time over the past year than I had planned. Knowing that others are using this will likely motivate me to prioritize this more.

Some upcoming enhancements I have planned:
* updated lodash
* a print function in case you want non-json output
* colorized output
* meaningful syntax errors

If you run into any rough edges, or have any feature requests, please file more issues.
